listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true
max_queued_messages 1000
max_inflight_messages 20
max_connections -1
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
autosave_interval 1800

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true
