[platformio]
default_envs = nodemcu_32s

[env:nodemcu_32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

build_flags = 
    -I include
    -I ../common
    -I ../iot_backend

lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson @ ^6.21.5

[env:native]
platform = native
test_framework = unity
test_build_src = no

build_flags =
    -I include
    -I ../common

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
