[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino  ; Sử dụng framework Arduino để tận dụng các thư viện sẵn có 
monitor_speed = 115200

; Định nghĩa các đường dẫn thư mục theo cấu trúc của bạn
build_flags = 
    -I ../common    ; Liên kết đến thư mục common dùng chung [cite: 82]

; Khai báo các thư viện cần thiết cho đồ án 
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8.0